### ISSUE TITLE
[BUG] don't compile in arm32v7/ubuntu

### ISSUE THREAD

**Issue by maxlapshin** [svpcom/wfb-ng#292]
**Describe the bug**
`make deb` breaks inside debhelper

**To Reproduce**

my Dockerfile:

```
FROM arm32v7/ubuntu:latest

RUN apt update && \
  apt install -y build-essential git wget \
    virtualenv fakeroot debhelper \
    libpcap-dev libsodium-dev \
    python3-twisted python3-pyroute2 \
    python3-future python3-all

RUN git clone https://github.com/svpcom/wfb-ng.git --depth 1 --branch wfb-ng-23.01
WORKDIR /wfb-ng

RUN make deb
```

I launch it on arm64 ubuntu:

```
docker build -t wfb-pkg .
Sending build context to Docker daemon  3.072kB
Step 1/5 : FROM arm32v7/ubuntu:latest
 ---> f3a711451e14
Step 2/5 : RUN apt update &&   apt install -y build-essential git wget     virtualenv fakeroot debhelper     libpcap-dev libsodium-dev     python3-twisted python3-pyroute2     python3-future python3-all
 ---> Using cache
 ---> 60eff4e3cc58
Step 3/5 : RUN git clone https://github.com/svpcom/wfb-ng.git --depth 1 --branch wfb-ng-23.01
 ---> Using cache
 ---> 0be485ecd2c7
Step 4/5 : WORKDIR /wfb-ng
 ---> Using cache
 ---> 1b1e6159cb53
Step 5/5 : RUN make deb
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 898c46793f8b
g++  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu++11 -c -o src/rx.o src/rx.cpp
cc  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu99 -c -o src/radiotap.o src/radiotap.c
src/radiotap.c: In function 'ieee80211_radiotap_iterator_init':
src/radiotap.c:116:34: warning: taking address of packed member of 'struct ieee80211_radiotap_header' may result in an unaligned pointer value [-Waddress-of-packed-member]
  116 |         iterator->_next_bitmap = &radiotap_header->it_present;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu99 -c -o src/fec.o src/fec.c
g++  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu++11 -c -o src/wifibroadcast.o src/wifibroadcast.cpp
g++ -o wfb_rx src/rx.o src/radiotap.o src/fec.o src/wifibroadcast.o  -lrt -lpcap -lsodium
g++  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu++11 -c -o src/tx.o src/tx.cpp
g++ -o wfb_tx src/tx.o src/fec.o src/wifibroadcast.o  -lrt -lpcap -lsodium
cc  -Wall -O2 -DWFB_VERSION='"23.1.16.78051-4886033f"' -std=gnu99 -c -o src/keygen.o src/keygen.c
cc -o wfb_keygen src/keygen.o  -lrt -lpcap -lsodium
virtualenv env --python=/usr/bin/python3
created virtual environment CPython3.10.6.final.0-32 in 1730ms
  creator CPython3Posix(dest=/wfb-ng/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
./env/bin/pip install --upgrade pip setuptools stdeb
Requirement already satisfied: pip in ./env/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./env/lib/python3.10/site-packages (59.6.0)
Collecting setuptools
  Downloading setuptools-67.6.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.2 MB/s eta 0:00:00
Collecting stdeb
  Downloading stdeb-0.10.0.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 KB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: stdeb
  Building wheel for stdeb (setup.py): started
  Building wheel for stdeb (setup.py): finished with status 'done'
  Created wheel for stdeb: filename=stdeb-0.10.0-py3-none-any.whl size=42848 sha256=122d9088c30182b81c987b697f93a4a81fd340f36cc7119ef4c24e58e3bd49fc
  Stored in directory: /root/.cache/pip/wheels/cc/2d/ec/d3fc47bd87b1d7b8d4e1847b4fe6942f162e56818684040c33
Successfully built stdeb
Installing collected packages: stdeb, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.0.1 setuptools-67.6.0 stdeb-0.10.0
rm -rf deb_dist
./env/bin/python ./setup.py --command-packages=stdeb.command bdist_deb
running bdist_deb
running sdist_dsc
running egg_info
creating wfb_ng.egg-info
writing wfb_ng.egg-info/PKG-INFO
writing dependency_links to wfb_ng.egg-info/dependency_links.txt
writing entry points to wfb_ng.egg-info/entry_points.txt
writing top-level names to wfb_ng.egg-info/top_level.txt
writing manifest file 'wfb_ng.egg-info/SOURCES.txt'
reading manifest file 'wfb_ng.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'wfb_ng.egg-info/SOURCES.txt'
running sdist
running check
creating wfb-ng-23.1.16.78051
creating wfb-ng-23.1.16.78051/scripts
creating wfb-ng-23.1.16.78051/scripts/default
creating wfb-ng-23.1.16.78051/wfb_ng
creating wfb-ng-23.1.16.78051/wfb_ng.egg-info
creating wfb-ng-23.1.16.78051/wfb_ng/conf
copying files to wfb-ng-23.1.16.78051...
copying LICENSE.txt -> wfb-ng-23.1.16.78051
copying README.md -> wfb-ng-23.1.16.78051
copying setup.py -> wfb-ng-23.1.16.78051
copying wfb_keygen -> wfb-ng-23.1.16.78051
copying wfb_rx -> wfb-ng-23.1.16.78051
copying wfb_tx -> wfb-ng-23.1.16.78051
copying scripts/98-wifibroadcast.conf -> wfb-ng-23.1.16.78051/scripts
copying scripts/wifibroadcast -> wfb-ng-23.1.16.78051/scripts
copying scripts/wifibroadcast.service -> wfb-ng-23.1.16.78051/scripts
copying scripts/wifibroadcast@.service -> wfb-ng-23.1.16.78051/scripts
copying scripts/default/wifibroadcast -> wfb-ng-23.1.16.78051/scripts/default
copying wfb_ng/__init__.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/cli.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/common.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/config_parser.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/latency_test.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/mavlink.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/mavlink_protocol.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/proxy.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/server.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng/tuntap.py -> wfb-ng-23.1.16.78051/wfb_ng
copying wfb_ng.egg-info/PKG-INFO -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng.egg-info/SOURCES.txt -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng.egg-info/dependency_links.txt -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng.egg-info/entry_points.txt -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng.egg-info/not-zip-safe -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng.egg-info/top_level.txt -> wfb-ng-23.1.16.78051/wfb_ng.egg-info
copying wfb_ng/conf/__init__.py -> wfb-ng-23.1.16.78051/wfb_ng/conf
copying wfb_ng/conf/master.cfg -> wfb-ng-23.1.16.78051/wfb_ng/conf
copying wfb_ng/conf/site.cfg -> wfb-ng-23.1.16.78051/wfb_ng/conf
Writing wfb-ng-23.1.16.78051/setup.cfg
creating dist
Creating tar archive
removing 'wfb-ng-23.1.16.78051' (and everything under it)
dpkg-buildpackage: info: source package wfb-ng
dpkg-buildpackage: info: source version 23.1.16.78051-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by None <None>
 dpkg-source --before-build .
dpkg-source: info: using options from wfb-ng-23.1.16.78051/debian/source/options: --extend-diff-ignore=\.egg-info$
 debian/rules clean
make[1]: Entering directory '/wfb-ng/deb_dist/wfb-ng-23.1.16.78051'
dh clean --with python3 --buildsystem=python_distutils
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/arm-linux-gnueabihf/perl5/5.34 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl-base /usr/lib/arm-linux-gnueabihf/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at (eval 10) line 1.
BEGIN failed--compilation aborted at (eval 10) line 1.

make[1]: *** [debian/rules:7: clean] Error 25
make[1]: Leaving directory '/wfb-ng/deb_dist/wfb-ng-23.1.16.78051'
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
Traceback (most recent call last):
  File "/wfb-ng/./setup.py", line 62, in <module>
    setup(
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/command/bdist_deb.py", line 34, in run
    self.run_command('sdist_dsc')
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/wfb-ng/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/command/sdist_dsc.py", line 137, in run
    build_dsc(debinfo,
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 1569, in build_dsc
    dpkg_buildpackage(*args, cwd=fullpath_repackaged_dirname)
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 585, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/wfb-ng/env/lib/python3.10/site-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
make: *** [Makefile:48: deb] Error 1
The command '/bin/sh -c make deb' returned a non-zero code: 2
make: *** [Makefile:2: all] Error 2
```

**Expected behavior**

Should finish with building deb package

**Confirm you read**
- [x]  https://github.com/svpcom/wfb-ng/blob/master/README.md
- [x]  https://github.com/svpcom/wfb-ng/wiki/Setup-HOWTO

**Comment by maxlapshin** [comment]
https://askubuntu.com/questions/1263305/launchpad-builderror-cant-locate-debian-debhelper-sequence-python3-pm

> Add dh-python to Build-Depends in the debian/control file.

I suppose, this is useless

**Comment by maxlapshin** [comment]
https://github.com/svpcom/wfb-ng/issues/62  should I stick to python2 instead of python3?

**Comment by svpcom** [comment]
You need to install `dh-python`:
``` .sh
$ dpkg -S /usr/share/perl5/Debian/Debhelper/Sequence/python3.pm
dh-python: /usr/share/perl5/Debian/Debhelper/Sequence/python3.pm
```

**Comment by svpcom** [comment]
@maxlapshin Now it should build deb files for any arch which supported in docker
